; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
; Common settings for all environments
monitor_filters = send_on_enter
monitor_eol = CRLF
monitor_echo = yes
lib_deps =
	paulstoffregen/Encoder@^1.4.4
	fastled/FastLED@^3.9.4

[env:micro]
build_type = release
extra_scripts = pre:set_hwids.py
platform = atmelavr
board = micro
framework = arduino
;upload_port = COM16 ; USB port for uploading the code
; Generate a map file including cross references for the build
; https://docs.platformio.org/en/latest/projectconf/advanced.html#build-flags
build_flags = -Wl,-Map,${BUILD_DIR}/output.map -Wl,-cref
debug_build_flags =
	-Wall
	-Os
	-ggdb3
	-g3
debug_tool = simavr
lib_ldf_mode = chain

[env:esp32-s3-devkitc-1]
build_type = release
platform = https://github.com/platformio/platform-espressif32.git
framework = arduino
board = esp32-s3-devkitc-1
upload_protocol = esptool
upload_speed = 2000000     ;ESP32S3 USB-Serial Converter maximum 2000000bps
monitor_speed = 115200
; Generate a map file including cross references for the build
; https://docs.platformio.org/en/latest/projectconf/advanced.html#build-flags
;build_flags =
;    -Wl,-Map,${BUILD_DIR}/output.map
;    -Wl,-cref
;debug_build_flags =
;	-Wall
;	-O0
;	-ggdb3
;	-g3
;debug_tool = esp-builtin
;debug_init_break = break setup
monitor_filters =
  esp32_exception_decoder
build_flags =
  -D CORE_DEBUG_LEVEL=5
  -D ARDUINO_USB_CDC_ON_BOOT=1


[platformio]
src_dir = src
default_envs = micro


; Information for esp32-s3-devkitc-1 board
; https://docs.platformio.org/en/latest/boards/espressif32/esp32-s3-devkitc-1.html
;
; The ESP32-S3-DevKitC-1 is used for debugging purposes. The device has an onboard JTAG interface for programming and debugging and has a lot more memory/space available
; for the debug symbols.
; The device has two USB connectors. The right one is used for Serial communication (RX/TX) and the left one is used for JTAG programming/debugging.
; You have to install the drivers (on Windows) for the JTAG interface to work. The left USB connector serves two interface: USB-Serial (interface 0) and JTAG (interface 2).
; Use ZADIG to install the driver for the JTAG interface. The USB-Serial interface is used for uploading the code and debugging. The JTAG interface is used for debugging.
; More information:
; https://community.platformio.org/t/how-to-use-jtag-built-in-debugger-of-the-esp32-s3-in-platformio/36042
;