; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; TODO: https://community.platformio.org/t/platformio-ini-and-sensitive-data/18255
; Think of a way to not have the password in this ini file.

[platformio]
name = SpaceMouse
description = PlatformIO project for SpaceMouse
default_envs = esp32-s3-devkitc-1, esp32-s3-zero, micro
src_dir = src

[env]
; Common settings for all environments
extra_scripts = pre:set_hwids.py
framework = arduino
build_flags =
	-Wl,-Map,${BUILD_DIR}/output.map -Wl,-cref		; create a map file	for size debugging


; Settings for all environments (Arduino Pro Micro & ESP32S3)
[common]
monitor_filters = send_on_enter
monitor_eol = CRLF
monitor_echo = yes
lib_deps =
	paulstoffregen/Encoder@^1.4.4

; Settings for the Arduino Pro Micro
[env:micro]
; Set the VID and PID for the Arduino Micro through the pre:set_hwids.py script
extra_scripts = pre:set_hwids.py
platform = atmelavr
board = micro
board_upload.use_1200bps_touch = true
board_upload.wait_for_upload_port = true
debug_build_flags =
	-Og	-ggdb3 -g3
	-D SIMULATOR_DEBUGGING
debug_tool = simavr
lib_ldf_mode = chain
lib_deps = fastled/FastLED@^3.9.19

; Settings for the Arduino Pro Micro, bootloader version (ie. when normal upload fails)
[env:micro_bootloader]
extends = env:micro
; Set the VID and PID for the Arduino Micro through the pre:set_hwids.py script
board_upload.use_1200bps_touch = false
board_upload.wait_for_upload_port = false

; Settings for the ATMega2560 (used for simulating, no USB support)
[env:atmega2560]
build_type = debug
; Set the VID and PID for the ATMega2560 through the pre:set_hwids.py script
extra_scripts = pre:set_hwids.py
platform = atmelavr
board = atmega2560
debug_build_flags =
	-Og	-ggdb3 -g3
	-D SIMULATOR_DEBUGGING
debug_tool = simavr
lib_ldf_mode = chain
lib_deps = fastled/FastLED@^3.9.19

; Common settings for all ESP32-S3 environments
[common_esp32s3]
platform = espressif32
build_unflags =
	-DARDUINO_USB_MODE=1
build_flags =
	-DARDUINO_USB_MODE=0
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_PSRAM
monitor_speed = 115200
lib_deps =
	adafruit/Adafruit TinyUSB Library@3.3.1
	 fastled/FastLED@^3.9.19
board = esp32-s3-devkitc-1
board_upload.use_1200bps_touch = true
board_upload.wait_for_upload_port = true
extra_scripts = post:reset_esp32.py


; Settings for the ESP32-S3-DevkitC-1 with USB upload
[env:esp32-s3-devkitc-1]
extends = common_esp32s3
upload_protocol = esptool
upload_speed = 2000000

;monitor_filters =
;	esp32_exception_decoder
;build_flags =
;	-D CORE_DEBUG_LEVEL=5


; Settings for the ESP32-S3-DevkitC-1 with OTA upload
[env:esp32-s3-devkitc-1-ota]
extends = common_esp32s3
upload_protocol = espota
upload_speed = 2000000
upload_port = 192.168.2.223
;upload_port = SpaceMouse.local
build_flags =
	-D INI_OTAHOSTNAME=\"SpaceMouse-Devkitc-1\"

; Settings for the ESP32-S3-Zero with USB upload
[env:esp32-s3-zero]
extends = common_esp32s3
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = default.csv

; Settings for the ESP32-S3-Zero with OTA upload
[env:esp32-s3-zero-ota]
extends = esp32-s3-zero
upload_protocol = espota
upload_speed = 2000000
upload_port = SpaceMouse-S3Zero.local
build_flags =
	-D INI_OTAHOSTNAME=\"SpaceMouse-S3Zero\"
